# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: wget -qO- https://ipecho.net/plain
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Dist
        path: dist
  deployment:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: Dist
      - name: deploy
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: '/home/runner/work/SurRealGateway/SurRealGateway/'
          remote: '~/surreal/api/'
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          pre_upload: echo "This will be executed before the upload!"
          post_upload: rm -rf ~/surreal/api/dist &&  mv ~/surreal/api/workspace ~/surreal/api/dist && print '${{secrets.DB_CONFIG_FILE}}' > ~/sureral/api/dist/config/db_config.js && sudo chmod -R 777 ~/surreal/api/dist && sudo service surreal restart
          ssh_options: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          scp_options: -v
